import {z, type ZodTypeAny} from 'zod';

/**
 * Property names that Continuum / DeFi tool schemas type as number/integer.
 * Used to coerce LLM string numerics without touching wei/amount string fields.
 * Keep in sync with mpc-auth agent_tool_arg_coerce.go.
 */
export const AGENT_NUMERIC_ARG_KEYS = new Set<string>([
	'askSize',
	'atrPeriod',
	'bollingerEntryProximityMode',
	'bollingerEntryProximityPct',
	'bollingerPeriod',
	'bollingerStdDev',
	'barsSinceConfirm',
	'baseFee',
	'baseFeeMultiplier',
	'basePeriod',
	'bidSize',
	'bucketSec',
	'candleCount',
	'candleLimit',
	'chainId',
	'collateralDecimals',
	'collateralIndex',
	'confidence',
	'conversionPeriod',
	'dPeriod',
	'day',
	'decimals',
	'depthAverageWindowSec',
	'depthLevelCount',
	'depthLimit',
	'depthSampleIntervalSec',
	'destChainId',
	'displacement',
	'distancePct',
	'divergenceMaxLag',
	'donchianPeriod',
	'donchianTargetAtrMultiple',
	'endTimeMs',
	'entryOffsetPct',
	'entryProximityAtrPeriod',
	'entryProximityPct',
	'everyMs',
	'executionFeeBufferBps',
	'expiryDate',
	'fastPeriod',
	'fee',
	'fibKeyLevelMinConfidence',
	'fibPairNumber',
	'firstNonce',
	'focusBar',
	'focusWindow',
	'freshCrossoverMaxBars',
	'fromIndex',
	'fromTime',
	'fromTimeSec',
	'gasLimit',
	'gasMultiplier',
	'gasPrice',
	'gate',
	'globalNonce',
	'gmDecimals',
	'gmxDecimals',
	'height',
	'high',
	'highLevelNumber',
	'hours',
	'ichimokuBasePeriod',
	'ichimokuConversionPeriod',
	'ichimokuDisplacement',
	'ichimokuSpanPeriod',
	'ichimokuTargetAtrMultiple',
	'index',
	'invalidationOffsetPct',
	'kPeriod',
	'lastClose',
	'levelNumber',
	'leverage',
	'limit',
	'lineWidth',
	'liquidityPercentageToDecrease',
	'lookback',
	'lookbackDays',
	'maFreshCrossoverMaxBars',
	'maFastPeriod',
	'maSlowPeriod',
	'low',
	'lowLevelNumber',
	'maxLag',
	'maxLevels',
	'maxLines',
	'maxPoints',
	'minConfidence',
	'minFinalityThreshold',
	'minTouches',
	'month',
	'multiplier',
	'oid',
	'orderDeadline',
	'pagenum',
	'pagesize',
	'pairNumber',
	'patternIndex',
	'patternNumber',
	'period',
	'pocPrice',
	'pollEveryMinutes',
	'pollMs',
	'price',
	'priceHi',
	'priceLo',
	'priorityFee',
	'retestAtrMultiplier',
	'retestAtrPeriod',
	'retestTolerancePct',
	'retracement618',
	'rsiPeriod',
	'sampleCount',
	'score',
	'signalPeriod',
	'signatureCount',
	'slippageBps',
	'slippagePercent',
	'slippageTolerance',
	'slope',
	'slowPeriod',
	'smoothWindow',
	'sourceChainId',
	'sourceDomain',
	'spanPeriod',
	'startTimeMs',
	'startingNonce',
	'stdDev',
	'stochasticPeriod',
	'stochasticRsiPeriod',
	'strength',
	'supertrendMultiplier',
	'supertrendPeriod',
	'supertrendTargetAtrMultiple',
	'swapDeadlineUnix',
	'swapTransactionDeadlineUnix',
	'swingLookback',
	'targetOffsetPct',
	'tickLower',
	'tickSpacing',
	'tickUpper',
	'time',
	'timeInForce',
	'timeMs',
	'timeSec',
	'timeout',
	'timeoutMs',
	'toIndex',
	'toTime',
	'toTimeSec',
	'tokenInDecimals',
	'tolerancePct',
	'totalSize',
	'touchCount',
	'tradeBarIndex',
	'tradeLevelNumber',
	'tradePatternNumber',
	'tradeRatio',
	'tradeTrendLineNumber',
	'trendLineNumber',
	'urnIndex',
	'volume',
	'waveMenuNumber',
	'windowSec',
	'year',
	'zScoreEntry',
	'zScoreExit',
	'zScorePeriod',
	'zScoreStopAtrMultiple',
]);

/** Property names typed as boolean in Continuum / DeFi tool schemas. */
export const AGENT_BOOLEAN_ARG_KEYS = new Set<string>([
	'accept',
	'acknowledgeHealthRisk',
	'activateBillingMonthAfterDeposit',
	'activateOnDeposit',
	'activeOnly',
	'aiReady',
	'allowRowsOnly',
	'cancelPendingTx',
	'chikou',
	'closeAboveMid',
	'colorVolumeFromCandles',
	'compact',
	'deleteAfterRun',
	'deleteConversation',
	'telegramNotify',
	'enableAsCollateralAfterSupply',
	'enableTpslMonitor',
	'enabled',
	'fill',
	'force',
	'includeHidden',
	'includeSecondaries',
	'initialLoad',
	'isBuy',
	'isContract',
	'isCross',
	'isLong',
	'isNativeIn',
	'isNativeOut',
	'isNearestResistance',
	'isNearestSupport',
	'isPrimary',
	'isPrimaryTradePair',
	'isRoleFlipped',
	'keepLeverage',
	'lastValueVisible',
	'legacy',
	'mergeLive',
	'omitTradeRatio',
	'overlay',
	'permissioned',
	'permit2Disabled',
	'refresh',
	'removeAllFibPairs',
	'removeAllLevels',
	'removeAllTrendLines',
	'removeDrawings',
	'removeElliottWaves',
	'removeFibPair',
	'removeLevel',
	'removeTrendLine',
	'robinhoodEarn',
	'showTradeRatio',
	'showVolumeConfirmation',
	'showVolumeProfile',
	'simulateTransaction',
	'skipDefaultOverlays',
	'skipHealthPreview',
	'skipSampler',
	'slowBatch',
	'smoothHeadShoulders',
	'testnet',
	'toPerp',
	'topLevel',
	'txParams',
	'unread',
	'useCustomGas',
	'usePermit2Approvals',
	'usePrimary',
	'useServerProxy',
	'useUserFolder',
	'usedDefaultOverlays',
	'withdrawAllCollateral',
]);

function looksLikePureJSONNumber(s: string): boolean {
	if (!s) return false;
	return /^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$/.test(s);
}

export function coerceAgentInputValue(value: unknown, key?: string): unknown {
	if (Array.isArray(value)) {
		return value.map(v => coerceAgentInputValue(v));
	}
	if (value != null && typeof value === 'object') {
		const out: Record<string, unknown> = {};
		for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
			out[k] = coerceAgentInputValue(v, k);
		}
		return out;
	}
	if (typeof value !== 'string' || !key) {
		return value;
	}
	const trimmed = value.trim();
	if (AGENT_BOOLEAN_ARG_KEYS.has(key)) {
		const t = trimmed.toLowerCase();
		if (t === 'true' || t === 'yes') return true;
		if (t === 'false' || t === 'no') return false;
	}
	if (AGENT_NUMERIC_ARG_KEYS.has(key) && looksLikePureJSONNumber(trimmed)) {
		if (trimmed.toLowerCase().startsWith('0x')) return value;
		const n = Number(trimmed);
		if (Number.isFinite(n)) return n;
	}
	return value;
}

/** Wrap a Zod 4 input schema so LLM string scalars coerce before MCP validation. */
export function wrapZodInputSchemaWithAgentCoerce(schema: ZodTypeAny): ZodTypeAny {
	return z.preprocess(val => coerceAgentInputValue(val), schema);
}
