import {
	ARKHAM_API_BASE_URL,
	ARKHAM_API_DOCS_URL,
	ARKHAM_API_LLMS_URL,
} from './api-key.js';
import type {ListArkhamApiPathsOutput} from './schemas.js';

/** Documented REST paths from https://arkm.com/llms.txt (WebSocket omitted). */
export const ARKHAM_API_PATHS: ListArkhamApiPathsOutput['paths'] = [
	{method: 'GET', path: '/analytics/credit-periods', description: 'Credit usage by billing period'},
	{method: 'GET', path: '/analytics/endpoint-calls', description: 'Endpoint call analytics'},
	{method: 'GET', path: '/arkm/circulating', description: 'ARKM circulating supply'},
	{method: 'GET', path: '/balances/address/{address}', description: 'Token balances for an address'},
	{method: 'GET', path: '/balances/entity/{entity}', description: 'Token balances for an entity'},
	{method: 'GET', path: '/chains', description: 'Supported chains'},
	{method: 'GET', path: '/cluster/{id}/summary', description: 'Cluster summary'},
	{method: 'GET', path: '/counterparties/address/{address}', description: 'Top counterparties for an address'},
	{method: 'GET', path: '/counterparties/entity/{entity}', description: 'Top counterparties for an entity'},
	{method: 'GET', path: '/flow/address/{address}', description: 'Historical USD flows for an address'},
	{method: 'GET', path: '/flow/entity/{entity}', description: 'Historical USD flows for an entity'},
	{method: 'GET', path: '/history/address/{address}', description: 'Historical data for an address'},
	{method: 'GET', path: '/history/entity/{entity}', description: 'Historical data for an entity'},
	{method: 'POST', path: '/intelligence/address/batch', description: 'Batch address intelligence'},
	{method: 'POST', path: '/intelligence/address/batch/all', description: 'Batch address intelligence, all chains'},
	{method: 'GET', path: '/intelligence/address/{address}', description: 'Address intelligence'},
	{method: 'GET', path: '/intelligence/address/{address}/all', description: 'Address intelligence, all chains'},
	{method: 'POST', path: '/intelligence/address_enriched/batch', description: 'Batch enriched address intelligence'},
	{method: 'POST', path: '/intelligence/address_enriched/batch/all', description: 'Batch enriched address intelligence, all chains'},
	{method: 'GET', path: '/intelligence/address_enriched/{address}', description: 'Enriched address intelligence'},
	{method: 'GET', path: '/intelligence/address_enriched/{address}/all', description: 'Enriched address intelligence, all chains'},
	{method: 'GET', path: '/intelligence/contract/{chain}/{address}', description: 'Contract intelligence'},
	{method: 'GET', path: '/intelligence/entity/{entity}', description: 'Entity intelligence'},
	{method: 'GET', path: '/intelligence/entity/{entity}/summary', description: 'Entity summary'},
	{method: 'GET', path: '/intelligence/entity_balance_changes', description: 'Entity balance changes'},
	{method: 'GET', path: '/intelligence/entity_predictions/{entity}', description: 'Entity predictions'},
	{method: 'GET', path: '/intelligence/entity_types', description: 'Entity types'},
	{method: 'GET', path: '/intelligence/search', description: 'Search addresses, entities, tokens, pools'},
	{method: 'GET', path: '/intelligence/token/{chain}/{address}', description: 'Token intelligence by chain/address'},
	{method: 'GET', path: '/intelligence/token/{id}', description: 'Token intelligence by pricing id'},
	{method: 'GET', path: '/loans/address/{address}', description: 'Loans for an address'},
	{method: 'GET', path: '/loans/entity/{entity}', description: 'Loans for an entity'},
	{method: 'GET', path: '/networks/status', description: 'Network status'},
	{method: 'GET', path: '/portfolio/address/{address}', description: 'Address portfolio history'},
	{method: 'GET', path: '/portfolio/entity/{entity}', description: 'Entity portfolio history'},
	{method: 'POST', path: '/risk/address/batch', description: 'Batch address risk scores'},
	{method: 'GET', path: '/risk/address/{address}', description: 'Address risk score'},
	{method: 'GET', path: '/risk/address/{address}/paths', description: 'Risk paths for an address'},
	{method: 'POST', path: '/risk/entity/batch', description: 'Batch entity risk scores'},
	{method: 'GET', path: '/risk/entity/{entity_id}', description: 'Entity risk score'},
	{method: 'GET', path: '/subscription/intel-usage', description: 'Current billing-period intel usage'},
	{method: 'GET', path: '/swaps', description: 'Swaps'},
	{method: 'GET', path: '/token/holders/{id}', description: 'Top token holders by pricing id'},
	{method: 'GET', path: '/token/market/{id}', description: 'Token market data'},
	{method: 'GET', path: '/token/top', description: 'Top tokens by exchange activity'},
	{method: 'GET', path: '/token/trending', description: 'Trending tokens'},
	{method: 'GET', path: '/transfers', description: 'Transfers (per-row billing — keep limits tight)'},
	{method: 'GET', path: '/transfers/histogram', description: 'Transfer histogram'},
	{method: 'GET', path: '/transfers/tx/{hash}', description: 'Transfers for a transaction'},
	{method: 'GET', path: '/tx/{hash}', description: 'Transaction details'},
	{method: 'GET', path: '/volume/address/{address}', description: 'Exchange/service volume for an address'},
	{method: 'GET', path: '/volume/entity/{entity}', description: 'Exchange/service volume for an entity'},
];

export function listArkhamApiPaths(): ListArkhamApiPathsOutput {
	return {
		baseUrl: ARKHAM_API_BASE_URL,
		docsUrl: ARKHAM_API_DOCS_URL,
		llmsUrl: ARKHAM_API_LLMS_URL,
		paths: ARKHAM_API_PATHS,
	};
}
